### ISSUE TITLE
Delete BDBag, catalog for failed submissions

### ISSUE THREAD

**Issue by jgaff** [nih-cfde/submission-workflow#13]
Delete both the DERIVA catalog and the stored BDBag when an ingest fails ~or is rejected by a curator~.

**Comment by lliming** [comment]
This totally makes sense when the ingest fails.

For the "rejected by a curator" part, is it clear yet that we want to use the curator steps of the flow for Epic 2? I'm aware of at least three possibilities:

(1) We use the curator steps as they exist now, with the email linking to an Automate page for reviewing and approving the submission.
(2) We use a modified version of the curator steps in which the email links to the CFDE portal (instead of an Automate page) for reviewing the submission. In this case, presumably the portal displays/embeds Automate's curation "buttons" (links, really) to approve/reject the submission. 
(3) We don't use Automate for curation at all, and instead let the review & approve UX be handled entirely by the CFDE portal.

Does this still need to be discussed with the CFDE UX team?

**Comment by jgaff** [comment]
I don't think it's clear that we are using or are not using the existing curation features of the submission flow. Additional discussion or clarification would be welcome.

**Comment by jgaff** [comment]
After discussion, all Flow-based curation is being removed (see #15), so the BDBag and catalog removal only needs to happen after a failed ingest, not after a failed curation step.

**Comment by karlcz** [comment]
I think we might want to defer deletion to some follow up automation as well (in response to state changes in the registry) so that we migth have partially-built content around for problem determination, and then have some lifecycle control via further user-input to the registry?

**Comment by jgaff** [comment]
This was a feature request from @rpwagner. Are we actually trying to get "automation in response to registry state changes" features in Epic 2?

**Comment by rpwagner** [comment]
I think we leave this in the users' hands for now. They should have a copy of the data that failed to load if they want to retest. From the Automate and Action Provider perspective, a failed ingest is a good point to clean things up. Anything after that can be part of another process.

**Comment by karlcz** [comment]
I agree we should close this for now.  If we have to reopen it, it seems like it would live in a different codebase downstream of the submission action provider, since it has to be done in response to other registry user interactions and/or automation bits?

**Comment by rpwagner** [comment]
OK, we can close it for now, but we should try to keep in mind how to handle potential failures like not being able to talk to the registry or even create the review catalog.
