### ISSUE TITLE
Cancelled submissions don't update/Can't cancel submissions

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#49]
I had a submission hang, and cancelled it in globus. This triggered an email from globus telling me the submission cancelled, but the submission tool didn't seem to update. The tool continues to say:

```
(cfdesubmit) (base) amandas-mbp-2:~ amanda$ cfde-submit status
Running on service 'staging'
Running on service 'staging'
Status of CFDE Submission (Flow ID 6000961b-3bf1-4acc-a2c5-92e54159480c)
This instance ID: 22ef6868-1a4a-4401-8782-e8ff5d712d2b
This Flow is still in progress.
Current Flow Step: TransferData
```

even after several minutes/several attempts

**Comment by NickolausDS** [comment]
This could be caused by a high wait time here: https://github.com/nih-cfde/deriva-action-provider/blob/master/globus_automate/flow.py#L45

Although it seems odd that the Transfer Action Provider isn't being more responsive to its current transfer changing state. @DavidKelly999 We should ping the automation folks and let them know.

**Comment by DavidMichaelKelly** [comment]
I will test this to see if I can reproduce the issue. The next release will use http as the primary method of file transfer, but I will look into this for users who may request to transfer via globus, and open an issue with the the automation team if needed.
