### ISSUE TITLE
Ingest action needs to distinguish cfde_deriva.exception.CfdeError instances

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/submission-workflow#52]
I think https://github.com/nih-cfde/deriva-action-provider/blob/6f1699b1ad7ad68fa0ec7dfd662323663b541e7a/cfde_ap/actions.py#L56  is the source of [a bug I entered in cfde-deriva](https://github.com/nih-cfde/cfde-deriva/issues/144)

We raise _expected_ exceptions from the class hierarchy in the cfde_deriva.exception module. These should be handled differently from other unexpected exceptions and this general handler clause should not be executed.  The ingest() routine will have already updated the submission status in the registry if we raise a CfdeError, so this extra call to `report_external_ops_error()` is overriding that with less accurate status info...

**Comment by NickolausDS** [comment]
That's unfortunate, it looks like that whole exception block isn't doing anything except causing problems. Removing it is an easy fix though.

**Comment by karlcz** [comment]
No, it shouldn't be removed, it is there to improve UX when an unexpected
error occurs and we otherwise have left the registry in an incorrect
state "in progress"!

What we need is a clause above it to treat our class hierarchy of
errors differently:

  except cfde_deriva.exception.CfdeError as e:
     # maybe you want other local logging here?
     raise
  except Exception as e:
     # same as before...

**Comment by karlcz** [comment]
Sorry, I made a mistake in the above... should have said `raise` and not `pass`!

**Comment by NickolausDS** [comment]
Maybe it's a difference of opinion, but I don't think the action provider should share responsibility of reporting errors to Deriva when the cfde-deriva package will always have more context and insight on what those errors are. Even when the error isn't an `cfde_deriva.exception.CfdeError`, the cfde-deriva package will likely be able to generate a better message than the Action Provider. The Action Provider on the other hand can only respond with an 'it failed' message, since success and failure are really the only two options with the context the action provider has. Since failure is handled in the calling function, it should simply raise and allow exceptions to be handled there instead. 

There is only one case where I think the Action Provider should report errors directly to Deriva, and that's when errors cannot be caught with exceptions. Besides #23, this should only be caused by out-of-memory errors. These errors are handled in status events instead by indirectly checking if a submission has taken longer than it should and marking it 'timed out'. Status events are part of a different process and should be largely immune to catastrophic errors like out-of-memory.

**Comment by karlcz** [comment]
OK, let me clarify.  The ingest() function already does the equivalent
of that clause for errors raised by ingest.  This clause is
unnecessary for those.

But, if errors come out of the calling context and/or environment
(such as subprocesses) and are not being seen by the cfde-deriva
exception handlers, it is the action provider which needs to report
them.  We want to avoid a gap where exceptions bubble out and are
known to the action provider and automate but not by the registry.

**Comment by NickolausDS** [comment]
I think that's where the difference of opinion comes in: Should non-deriva exceptions be reported by the cfde-deriva code (in a top level except block in `ingest()`), or by the action provider (using the same approach)? My opinion is more for the former since cfde-deriva has more context. And that would avoid future problems where cfde-deriva finds a problem, reports it, then the Action Provider overwrites it will a vague and less-useful message.

**Comment by karlcz** [comment]
OK, I think we're talking at cross purposes.  I agree you don't need
that clause right their as it is only wrapping the ingest() routine.

What I think you need is a similar clause much higher in your
action-provider code to handle the failure mode we know about: the
ingest() never returns because a sub-process was killed and the
cfde_deriva code was not allowed to run its own exception handlers.

We want to attempt to report that error because we do not know how
far the child process got before it was aborted.

**Comment by karlcz** [comment]
To restate the user-visible requirement: the UX should not report an error via automate while leaving the registry in an apparently non-error state.  It is OK if an error happens before a registry entry exists (no evidence of submission) and OK if the registry entry is marked in a failed state, but not OK if automate knows it failed but the registry indicates it is still in progress due to orphaned state that will never get another update...

**Comment by NickolausDS** [comment]
> What I think you need is a similar clause much higher in your
action-provider code to handle the failure mode we know about: the
ingest() never returns because a sub-process was killed and the
cfde_deriva code was not allowed to run its own exception handlers.

Handled by https://github.com/nih-cfde/deriva-action-provider/pull/16 

Separately for this: 

> To restate the user-visible requirement: the UX should not report an error via automate while leaving the registry in an apparently non-error state.

Definitely agree. Just so we're on the same page, were you going to make this guarantee within `ingest()`?

**Comment by karlcz** [comment]
It does the best it can here https://github.com/nih-cfde/cfde-deriva/blob/3333f23bb69e0716b26c91aa793b856847a5bddf/cfde_deriva/submission.py#L331  to always update the registry status on exit from the ingest() routine, but this of course doesn't apply if the subprocess is aborted.  It is something only the still-running parent process can take care of at that point, since the finally clause never runs...

**Comment by NickolausDS** [comment]
Ok, I think we're all set then. As mentioned above, we just need to remove the exception block here: https://github.com/nih-cfde/deriva-action-provider/blob/6f1699b1ad7ad68fa0ec7dfd662323663b541e7a/cfde_ap/actions.py#L56 to ensure the AP doesn't overwrite the error. Aborted subprocesses will be handled here: https://github.com/nih-cfde/deriva-action-provider/blob/6f1699b1ad7ad68fa0ec7dfd662323663b541e7a/cfde_ap/api.py#L199.
