### ISSUE TITLE
Change error text or behavior for DCC ID names

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#78]
We've had several people with this issue. Basically, they put in their DCC id incorrectly and the error is:

`Error ingesting to DERIVA: not enough values to unpack (expected 2, got 1)`

It usually means that they put in just `hmp` rather than `cfde_registry_dcc:hmp`

I imagine there are two possible ways to fix this:

1. Change the error text to tell them that that they need to add `cfde_registry_dcc:` to the name
2. Change the tool so that it takes just the dcc abbreviation and adds the `cfde_registry_dcc:` itself. Since every ID starts with `cfde_registry_dcc:` it seems slightly weird to make them enter it anyway.

related issues:
https://github.com/nih-cfde/published-documentation/discussions/205
https://github.com/nih-cfde/published-documentation/discussions/150

**Comment by DavidMichaelKelly** [comment]
In the latest release, dcc names are validated via the ermrest api. If the user enters an invalid dcc, they will get an error message before job submission.

Users may now also use the short dcc name directly, for example gtex instead of cfde_registry_dcc:gtex. 
The longer cfde_registry_dcc:foo name will continue to work.

**Comment by ACharbonneau** [comment]
tested and works, but I'm leaving open until I update those bug reports

**Comment by ACharbonneau** [comment]
bug report updated
