### ISSUE TITLE
cfde-submit client-side validation can be slow with large data

### ISSUE THREAD

**Issue by DavidMichaelKelly** [nih-cfde/submission-workflow#91]
@ACharbonneau has reported on slack an issue where a user submission appears to hang when initially submitting. She tried reproducing the issue on her laptop, and it took 25 minutes to complete.

By default, cfde-submit uses frictionless for validation. There is a command line option, --disable-validation, which turns it off.

Discussions are ongoing about the best way to resolve this. One option might be to disable local validation by default. We are checking with Arthur to learn more about what validation occurs in his builder script.

**Comment by karlcz** [comment]
The current state seems to be as follows.

The builder script does:
- some complementary checks (higher-level logic tests)
- some overlapping checks (controlled vocab term referential integrity)

The cfde-submit tool runs default frictionless validation which:
- checks tabular structures
- checks uniqueness constraints
- checks foreign key constraints (controlled vocab terms and other c2m2 relationships)

The server-side ingest process does all the checks that cfde-submit does, and some higher level checks which may partially overlap the builder tests.

Disabling the checks by default now will defer error reporting to the ingest flow, and the UX will depend on whether our relayed error messages are equivalent to what comes out of frictionless.  I think some errors like foreign key errors from ingest may have _better_ UX because we've implemented checks in a different way which provides more specific context/guidance.  But, I cannot say that all errors are handled equivalently or better...

**Comment by DavidMichaelKelly** [comment]
The last update I have on this issue from @ACharbonneau on January 20th was that validation should remain enabled in the client by default. Information about disabling validation has been added to the docs.
